# Generated by Django 4.1.2 on 2022-10-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_composition_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='default playlist', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composition',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.playlist'),
        ),
    ]
