# Generated by Django 4.1.2 on 2022-10-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_composition_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
