# Generated by Django 4.1.2 on 2022-11-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_playlist_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['title']},
        ),
    ]
