# Generated by Django 4.1.2 on 2022-11-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_composition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={},
        ),
    ]
