# Generated by Django 4.1.2 on 2022-11-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_composition_options_composition_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={},
        ),
        migrations.RemoveField(
            model_name='composition',
            name='order',
        ),
    ]
