# Generated by Django 4.1.2 on 2022-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_composition_options_remove_composition_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='composition',
            name='order',
            field=models.PositiveSmallIntegerField(default=False),
            preserve_default=False,
        ),
    ]
