# Generated by Django 4.1.2 on 2022-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_composition_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='cover_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='composition',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
